/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reporting.app;
import reporting.proto.LinkedList;

import static reporting.utilities.StringUtils.join;
import static reporting.utilities.StringUtils.split;
import static reporting.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));

    }
}
